[build]
  command = "npm run build"
  publish = "out"
  
[functions]
  directory = "netlify/functions"
  
# Custom headers for better cache control
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Main site pages - short cache
[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Dynamic pages - short cache
[[headers]]
  for = "/story/*"
  [headers.values]
    Cache-Control = "public, max-age=300, must-revalidate"

[[headers]]
  for = "/browse"
  [headers.values]
    Cache-Control = "public, max-age=300, must-revalidate"

# Admin - no cache
[[headers]]
  for = "/admin/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Static assets - long cache
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
  
# Redirects API calls to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle dynamic story routes for client-side routing
[[redirects]]
  from = "/story/*"
  to = "/404.html"
  status = 200
  force = false
  conditions = {SkipExistingFiles = true}

# Ensure Netlify CMS admin interface is properly served
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
  force = true

# Handle any route with the SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
