[build]
  command = "npm run build"
  publish = "out"
  
[functions]
  directory = "netlify/functions"
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Ensure Netlify CMS admin interface is properly served
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
  force = true
