[build]
  command = "npm run build"
  publish = "out"
  
[functions]
  directory = "netlify/functions"
  
# Redirects API calls to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle dynamic story routes for client-side routing
[[redirects]]
  from = "/story/*"
  to = "/404.html"
  status = 200
  force = false
  conditions = {SkipExistingFiles = true}

# Ensure Netlify CMS admin interface is properly served
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
  force = true

# Handle any route with the SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
