[build]
  command = "npm run build"
  publish = "out"
  
[functions]
  directory = "netlify/functions"
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirect Netlify CMS to admin path
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
