backend:
  name: git-gateway
  branch: main

# Media and public folder configuration
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

# Collections define the content structure
collections:
  - name: "stories"
    label: "Published Stories"
    folder: "content/stories"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "ID", name: "id", widget: "string", required: true}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Company Name", name: "companyName", widget: "string", required: true}
      - {label: "Industry", name: "industry", widget: "select", options: ["saas", "ecommerce", "fintech", "healthtech", "edtech", "consumer", "marketplace", "hardware", "other"], required: true}
      - {label: "Funding Amount", name: "fundingAmount", widget: "string", required: false}
      - {label: "Failure Reason", name: "failureReason", widget: "select", options: ["product-market-fit", "funding", "team", "competition", "business-model", "timing", "technology", "other"], required: true}
      - {label: "Submission Date", name: "date", widget: "datetime", required: true}
      - {label: "Published", name: "published", widget: "boolean", default: true}
      - {label: "Email", name: "email", widget: "string", required: false}
      - {label: "Slug", name: "slug", widget: "string", required: true}
      - {label: "Story", name: "body", widget: "markdown", required: true}
  
  - name: "submissions"
    label: "New Submissions"
    folder: "content/submissions"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "ID", name: "id", widget: "string", required: true}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Company Name", name: "companyName", widget: "string", required: true}
      - {label: "Industry", name: "industry", widget: "select", options: ["saas", "ecommerce", "fintech", "healthtech", "edtech", "consumer", "marketplace", "hardware", "other"], required: true}
      - {label: "Funding Amount", name: "fundingAmount", widget: "string", required: false}
      - {label: "Failure Reason", name: "failureReason", widget: "select", options: ["product-market-fit", "funding", "team", "competition", "business-model", "timing", "technology", "other"], required: true}
      - {label: "Submission Date", name: "date", widget: "datetime", required: true}
      - {label: "Published", name: "published", widget: "boolean", default: false}
      - {label: "Email", name: "email", widget: "string", required: false}
      - {label: "Slug", name: "slug", widget: "string", required: true}
      - {label: "Story", name: "body", widget: "markdown", required: true}
      - label: "Approval Action"
        name: "approve"
        widget: "select"
        options:
          - { label: "Pending Review", value: "pending" }
          - { label: "Approve & Publish", value: "approve" }
          - { label: "Reject", value: "reject" }
        default: "pending"